export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'

export const FORMULARIO_NOTA = 'FORMULARIO_NOTA'
export const OBTENER_NOTAS = 'OBTENER_NOTAS'
export const AGREGAR_NOTA = 'AGREGAR_NOTA'
export const ELIMINAR_NOTA = 'ELIMINAR_NOTA'






